(function() {var implementors = {};
implementors["failure"] = [];
implementors["mdbook_linkcheck"] = [{text:"impl <a class=\"trait\" href=\"failure/trait.Fail.html\" title=\"trait failure::Fail\">Fail</a> for <a class=\"struct\" href=\"mdbook_linkcheck/errors/struct.BrokenLinks.html\" title=\"struct mdbook_linkcheck::errors::BrokenLinks\">BrokenLinks</a>",synthetic:false,types:["mdbook_linkcheck::errors::BrokenLinks"]},{text:"impl <a class=\"trait\" href=\"failure/trait.Fail.html\" title=\"trait failure::Fail\">Fail</a> for <a class=\"struct\" href=\"mdbook_linkcheck/errors/struct.EmptyLink.html\" title=\"struct mdbook_linkcheck::errors::EmptyLink\">EmptyLink</a>",synthetic:false,types:["mdbook_linkcheck::errors::EmptyLink"]},{text:"impl <a class=\"trait\" href=\"failure/trait.Fail.html\" title=\"trait failure::Fail\">Fail</a> for <a class=\"struct\" href=\"mdbook_linkcheck/errors/struct.UnsuccessfulStatus.html\" title=\"struct mdbook_linkcheck::errors::UnsuccessfulStatus\">UnsuccessfulStatus</a>",synthetic:false,types:["mdbook_linkcheck::errors::UnsuccessfulStatus"]},{text:"impl <a class=\"trait\" href=\"failure/trait.Fail.html\" title=\"trait failure::Fail\">Fail</a> for <a class=\"struct\" href=\"mdbook_linkcheck/errors/struct.FileNotFound.html\" title=\"struct mdbook_linkcheck::errors::FileNotFound\">FileNotFound</a>",synthetic:false,types:["mdbook_linkcheck::errors::FileNotFound"]},{text:"impl <a class=\"trait\" href=\"failure/trait.Fail.html\" title=\"trait failure::Fail\">Fail</a> for <a class=\"struct\" href=\"mdbook_linkcheck/errors/struct.HttpError.html\" title=\"struct mdbook_linkcheck::errors::HttpError\">HttpError</a>",synthetic:false,types:["mdbook_linkcheck::errors::HttpError"]},{text:"impl <a class=\"trait\" href=\"failure/trait.Fail.html\" title=\"trait failure::Fail\">Fail</a> for <a class=\"struct\" href=\"mdbook_linkcheck/errors/struct.ForbiddenPath.html\" title=\"struct mdbook_linkcheck::errors::ForbiddenPath\">ForbiddenPath</a>",synthetic:false,types:["mdbook_linkcheck::errors::ForbiddenPath"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
